name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Configure Custom Domain
        run: |
          echo 'raptorino.com' > ./dist/CNAME

      - name: Commit and push to the "gh-pages" branch
        env: 
            USER_NAME_SECRET: ${{ secrets.USER_NAME }}
            USER_EMAIL_SECRET: ${{ secrets.USER_EMAIL }}
        run: |
          git config user.name "$USER_NAME_SECRET"
          git config user.email "$USER_EMAIL_SECRET"
          git checkout -b gh-pages
          git add .
          git commit -m "Update from main branch"
          git push --force origin gh-pages