name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Production
        run: npm run build

      - name: Create and Push to Deployment Branch
        run: |
          git checkout -b deploy-build-vps

          git rm -r .

          cp -r $GITHUB_WORKSPACE/dist/* .

          git add .

          git commit -m "Deploy production build to vps"

          git push origin deploy

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            rm -rfv /home/raptor/Github/raptorino/

            scp -rv $GITHUB_WORKSPACE/dist/* /home/raptor/Github/raptorino/

            systemctl reload nginx
