name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Configure Custom Domain
        run: |
          echo 'raptorino.com' > ./dist/CNAME

      - name: Initialize Git repository in the "gh-pages" branch
        run: |
          git init
          git config user.name "$USER_NAME_SECRET"
          git config user.email "$USER_EMAIL_SECRET"
          git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages

      - name: Copy build files to "gh-pages" branch
        run: |
          rm -rf ./*
          cp -r ./dist/* ./
          git add .
          git commit -m "Update from main branch"
          git push --force origin gh-pages
