name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Connect to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}

      - name: Execute deploy-and-build script
        run: |
          scp deploy-and-build-raptorino.sh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:~/deploy-and-build-raptorino.sh
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} 'bash -s' < ~/deploy-and-build-raptorino.sh

