name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Create and Push Deployment Branch
        run: |
          git checkout -b website-build

          git rm -r .

          cp -r $GITHUB_WORKSPACE/dist/* .

          git add .

          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "${{ secrets.USER_NAME }}"

          git commit -m "Deploy production build"

          git push origin deploy

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            git clone --branch deploy https://github.com/Raptor1818/raptorino.git /home/raptor/Github/raptorino/

            cd /home/raptor/Github/raptorino/
            git branch -d deploy
